import uuid
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from datetime import datetime
from app.db import get_db
from app.models import ThreadPostDraft, ThreadPostLog

router = APIRouter(prefix="/api/drafts", tags=["Drafts"])

@router.get("/")
def get_drafts(skip: int = 0, limit: int = 50, status: str = None, db: Session = Depends(get_db)):
    """Retrieve a list of drafts, optionally filtered by status."""
    query = db.query(ThreadPostDraft)
    if status:
        query = query.filter(ThreadPostDraft.status == status)
    drafts = query.order_by(ThreadPostDraft.created_at.desc()).offset(skip).limit(limit).all()
    return drafts

@router.post("/{draft_id}/approve")
def approve_draft(draft_id: uuid.UUID, db: Session = Depends(get_db)):
    """Manually approve a draft for publishing."""
    draft = db.query(ThreadPostDraft).filter(ThreadPostDraft.id == draft_id).first()
    if not draft:
        raise HTTPException(status_code=404, detail="Draft not found")
        
    draft.status = "approved"
    draft.approved_at = datetime.utcnow()
    db.add(ThreadPostLog(draft_id=draft.id, action="approve", detail="Approved via API"))
    db.commit()
    return {"status": "ok", "message": f"Draft {draft_id} approved."}

@router.post("/{draft_id}/reject")
def reject_draft(draft_id: uuid.UUID, db: Session = Depends(get_db)):
    """Manually reject a draft."""
    draft = db.query(ThreadPostDraft).filter(ThreadPostDraft.id == draft_id).first()
    if not draft:
        raise HTTPException(status_code=404, detail="Draft not found")
        
    draft.status = "rejected"
    db.add(ThreadPostLog(draft_id=draft.id, action="reject", detail="Rejected via API"))
    db.commit()
    return {"status": "ok", "message": f"Draft {draft_id} rejected."}

@router.post("/{draft_id}/regenerate")
def regenerate_draft(draft_id: uuid.UUID, db: Session = Depends(get_db)):
    """Mark a draft to be regenerated by the AI."""
    draft = db.query(ThreadPostDraft).filter(ThreadPostDraft.id == draft_id).first()
    if not draft:
        raise HTTPException(status_code=404, detail="Draft not found")
        
    draft.status = "pending_regeneration"
    db.add(ThreadPostLog(draft_id=draft.id, action="regenerate", detail="Regeneration requested via API"))
    db.commit()
    return {"status": "ok", "message": f"Draft {draft_id} marked for regeneration."}