import asyncio
from sqlalchemy.orm import Session
from app.db import SessionLocal
from app.models import ThreadPostIdea
from app.services.ai_generator import generate_ideas
from app.services.telegram_approval import send_telegram_message

async def run_ideation(chat_id: str = None):
    db: Session = SessionLocal()
    try:
        print("Generating new post ideas...")
        result = generate_ideas(count=3)
        ideas_data = result.get("ideas", [])
        
        if not ideas_data:
            print("No ideas generated.")
            await send_telegram_message("❌ *Ideation Job completed*, but no ideas were generated.", chat_id)
            return
            
        ideas_summary = []
        for item in ideas_data:
            topic = item.get("topic")
            angle = item.get("angle")
            idea = ThreadPostIdea(
                topic=topic,
                angle=angle,
                source_note="Generated by Ideation Agent",
                status="pending"
            )
            db.add(idea)
            print(f"Added idea: {topic}")
            ideas_summary.append(f"💡 *{topic}*\n_Angle:_ {angle}")
            
        db.commit()

        summary_text = "\n\n".join(ideas_summary)
        report_msg = (
            f"✅ *Ideation Job Done!*\n\n"
            f"Brainstormed and saved {len(ideas_data)} new topics:\n\n"
            f"{summary_text}\n\n"
            f"👉 Use `/generate` to write drafts for these!"
        )
        await send_telegram_message(report_msg, chat_id)
        print(f"Successfully added {len(ideas_data)} new ideas to the database.")

    except Exception as e:
        error_msg = f"❌ *Ideation Job Failed!*\nError: `{str(e)}`"
        print(error_msg)
        await send_telegram_message(error_msg, chat_id)
    finally:
        db.close()

if __name__ == "__main__":
    asyncio.run(run_ideation())