import asyncio
from sqlalchemy.orm import Session
from app.db import SessionLocal
from app.models import ThreadPostIdea
from app.services.ai_generator import generate_ideas

async def run_ideation():
    db: Session = SessionLocal()
    try:
        print("Generating new post ideas...")
        result = generate_ideas(count=3)
        ideas_data = result.get("ideas", [])
        
        if not ideas_data:
            print("No ideas generated.")
            return
            
        for item in ideas_data:
            idea = ThreadPostIdea(
                topic=item.get("topic"),
                angle=item.get("angle"),
                source_note="Generated by Ideation Agent",
                status="pending"
            )
            db.add(idea)
            print(f"Added idea: {item.get('topic')}")
            
        db.commit()
        print(f"Successfully added {len(ideas_data)} new ideas to the database.")
    except Exception as e:
        print(f"Failed to generate ideas: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    asyncio.run(run_ideation())